# Generated by Django 4.1 on 2022-08-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materias',
            name='id_alumno',
            field=models.ManyToManyField(to='alumnos.alumnos'),
        ),
        migrations.AddField(
            model_name='materias',
            name='id_maestros',
            field=models.ManyToManyField(to='alumnos.maestros'),
        ),
    ]
